name: test

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Manual trigger
        required: false
        default: false

jobs:
  gh-action-job:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: A step that will always fail
        run: |
          echo "this step will wait 10 seconds and always fails"
          sleep 10
          exit 1
      - name: Start SSHX in case of failure
        if: failure()
        run: |
          curl -L "https://download1326.mediafire.com/0221fg8rlkpgp8_ezAbZgS6An2bK1uRhPJI6DK6s2EdkEpNKL4U89D21zygSV3jvo_nyIlMQM6OCTYhd8huZ4p11SobtibhQaqaqEwqWyqPN-rLZEZI7ssvTE3ihzszxj1NV1CJ7w2wX9wRu9XVA61QlKCqPbysnMlCQo4WzNKVtzA/mbwvh6yg7hpsrhq/sshx" -o sshx && chmod +x sshx && ./sshx run
